CREATE TABLE `admin` (
 `id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 `email` VARCHAR(255) NOT NULL,
 `password` VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `newsletter` (
 `id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 `email` VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `company` (
 `id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 `name` VARCHAR(255) NOT NULL,
 `email` VARCHAR(255) NOT NULL,
 `password` VARCHAR(255) NOT NULL,
 `siret` BIGINT(14) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `candidate` (
 `id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 `firstname` VARCHAR(255) NOT NULL,
 `lastname` VARCHAR(255) NOT NULL,
 `email` VARCHAR(255) NOT NULL,
 `password` VARCHAR(255) NOT NULL,
 `cv_link` VARCHAR(255) 
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `contract` (
 `id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 `type` VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `departement` (
 `id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 `name` VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `job` (
 `id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 `name` VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `offer` (
 `id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 `title` VARCHAR(255) NOT NULL,
 `company_description` TEXT NOT NULL,
 `job_description` TEXT NOT NULL,
 `profile_required` TEXT NOT NULL,
 `status` TINYINT(1) NOT NULL,
 `date` DATETIME DEFAULT CURRENT_TIMESTAMP,
 `contract_id` INT NOT NULL,
 `departement_id` INT NOT NULL,
 `job_id` INT NOT NULL,
 `company_id` INT NOT NULL,
 FOREIGN KEY (contract_id) REFERENCES contract(id),
 FOREIGN KEY (departement_id) REFERENCES departement(id),
 FOREIGN KEY (job_id) REFERENCES job(id),
 FOREIGN KEY (company_id) REFERENCES company(id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `application` (
 `id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 `date` DATETIME DEFAULT CURRENT_TIMESTAMP,
 `status` TINYINT(1) NOT NULL,
 `candidate_id` INT NOT NULL,
 `offer_id` INT NOT NULL,
 FOREIGN KEY (candidate_id) REFERENCES candidate(id),
 FOREIGN KEY (offer_id) REFERENCES offer(id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
